include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ObackSettings

ObackSettings_FILES = ObackSettingsController.m
ObackSettings_INSTALL_PATH = /Library/PreferenceBundles
ObackSettings_FRAMEWORKS = UIKit
ObackSettings_PRIVATE_FRAMEWORKS = Preferences
ObackSettings_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
